version: "3.9"
services:
  co-dev-db:
    image: postgres
    restart: always
    container_name: co-dev-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: co_dev
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
